#!/usr/bin/env node
// Regenerates docs/copy-review.md: every Bangla string next to its English
// source, for review by native speakers. Run: node scripts/copy-review.mjs
import { readFileSync, writeFileSync } from "node:fs";

const bn = JSON.parse(readFileSync(new URL("../messages/bn.json", import.meta.url)));
const en = JSON.parse(readFileSync(new URL("../messages/en.json", import.meta.url)));

const flat = (o, p = "") =>
  Object.entries(o).flatMap(([k, v]) => (typeof v === "object" ? flat(v, `${p}${k}.`) : [[`${p}${k}`, v]]));
const enMap = new Map(flat(en));
const rows = flat(bn);
const missing = [...enMap.keys()].filter((k) => !rows.some(([bk]) => bk === k));
const esc = (s) => String(s).replace(/\|/g, "\\|").replace(/\n/g, " ");

const intro = `# Bangla copy review

Generated by \`node scripts/copy-review.mjs\` from \`/messages/bn.json\` and \`/messages/en.json\`.
Bangla is the default language; the English text is the source of meaning. Please review for
**plain, respectful, everyday Bangla** (Class 6 reading level), consistent terms, and correct
Bangla numerals/plurals. Mark each row ✅ / ✏️ (suggest text) in a PR or issue.

## Priority items (please check first)

| Key | Why |
| --- | --- |
| \`home.emergency\` | Health advice: confirm the national helpline name and number (স্বাস্থ্য বাতায়ন ১৬২৬৩) with DGHS before launch. |
| \`risk.layer\`, \`risk.explain\` | Must not be read as "confirmed cases". Keep "নিশ্চিত রোগী নয়" wording prominent. |
| \`report.privacy\`, \`report.noteHint\` | Privacy promise; must be accurate and easy to understand. |
| \`report.larvaeLabel\` | Is "লার্ভা (ছোট নড়াচড়া করা পোকা)" understood? Alternatives: "মশার শূককীট", "পানিতে কিলবিল করা পোকা". |
| \`siteType.*\` | Everyday names for tire/bucket/drum/AC tray/flower tub in Dhaka households. |
| \`staff.roles.moderator\` | "যাচাইকারী" vs "মডারেটর" (volunteers may know the English loanword). |
| \`done.tip1\`–\`tip4\` | Match DGHS/city-corporation messaging ("৩ দিন পরপর পানি বদলান"). |
| \`status.*\` | Short enough for badges on a 360 px screen. |

## Missing Bangla keys

${missing.length ? missing.map((k) => `- \`${k}\``).join("\n") : "None."}

## All strings (${rows.length})

| Key | English | বাংলা | Review |
| --- | --- | --- | --- |
`;
writeFileSync(
  new URL("../docs/copy-review.md", import.meta.url),
  intro + rows.map(([k, v]) => `| \`${k}\` | ${esc(enMap.get(k) ?? "—")} | ${esc(v)} | |`).join("\n") + "\n",
);
console.log(`docs/copy-review.md: ${rows.length} strings, ${missing.length} missing`);
